### ISSUE TITLE
[BUG/UPDATE] 1.16 Support ?

### ISSUE THREAD

**Issue by leasoncre** [divisionind/BackpacksRemastered#10]
1.16 support comming soon?
looks like NMS is outdated?
Thanks.
(I realize it's still early and 1.16 bukkit/spigot are still in 'early' release stages.) Happy coding!

```[13:15:35] [Server thread/INFO]: [BackpacksRemastered] Enabling BackpacksRemastered v2020.0.4
[13:15:35] [Server thread/INFO]: [BackpacksRemastered] Detected NMS v1_16_R1. Using this for all NMS related functions.
[13:15:35] [Server thread/ERROR]: [BackpacksRemastered] 2 error(s) initializing NMS. Was the detected server wrong? If not, then NMS has changed significantly sense this plugin was released and therefore, it can not fully adapt.
[13:15:35] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.MinecraftServer.getWorldServer(net.minecraft.server.v1_16_R1.DimensionManager)
[13:15:35] [Server thread/WARN]: 	at java.lang.Class.getMethod(Unknown Source)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMSMethod.lambda$static$1(NMSMethod.java:40)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMSMethod.init(NMSMethod.java:71)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMS.initialize(NMS.java:70)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:107)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[13:15:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:15:35] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.TileEntityFurnace.load(net.minecraft.server.v1_16_R1.NBTTagCompound)
[13:15:35] [Server thread/WARN]: 	at java.lang.Class.getMethod(Unknown Source)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMSMethod.lambda$new$4(NMSMethod.java:58)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMSMethod.init(NMSMethod.java:71)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.nms.reflect.NMS.initialize(NMS.java:70)
[13:15:35] [Server thread/WARN]: 	at com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:107)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:491)
[13:15:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:405)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:438)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:219)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:810)
[13:15:35] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164)
[13:15:35] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[13:15:39] [Server thread/INFO]: [BackpacksRemastered] BackpacksRemastered v2020.0.4 (git: 6cc50f5) was enabled in 4.54s!```

**Comment by drew6017** [comment]
I will try to get to it as soon as possible. From these errors, it looks like everything should still work except for the furnace backpack. So, if that's not important to you, you should be good.

**Comment by Darth-Sicaedus** [comment]
I have been using the current in my 1.16.1 Paper test server. Even though I don't personally use the furnace backpack, I just tested it and can confirm that it does not work. Everything else seems perfectly functional though.

**Comment by XipsAhoy** [comment]
Can you also add support for new blocks like shulker, smoker, loom, etc! The plugin is awesome btw!

**Comment by JxM-92** [comment]
Does the latest version, 2020.04 works for 1.16?

**Comment by drew6017** [comment]
1.16.X support added in version 2020.0.5. The file is being approved by bukkit and should be live in 1-2 days.
