### ISSUE TITLE
Support for 1.19.4

### ISSUE THREAD

**Issue by Darth-Sicaedus** [divisionind/BackpacksRemastered#47]
Plugin sends up error about NMS needing to be updated when loaded. Looks like that just breaks the Furnace Backpack from what I can tell.

[10:04:37 INFO]: [BackpacksRemastered] Enabling BackpacksRemastered v2022.1.8
[10:04:37 INFO]: [BackpacksRemastered] Detected NMS v1_19_R3. Using this for all NMS related functions.
[10:04:37 ERROR]: [BackpacksRemastered] 2 error(s) initializing NMS. Was the detected server wrong? If not, then NMS has changed significantly sense this plugin was released and therefore, it can not fully adapt.
[10:04:37 WARN]: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
[10:04:37 WARN]: 	at java.base/java.lang.reflect.Field.checkAccess(Field.java:1103)
[10:04:37 WARN]: 	at java.base/java.lang.reflect.Field.get(Field.java:423)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMS.initialize(NMS.java:81)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:105)
[10:04:37 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[10:04:37 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[10:04:37 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:04:37 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:04:37 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[10:04:37 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[10:04:37 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[10:04:37 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:04:37 WARN]: com.divisionind.bprm.nms.reflect.ex.NMSLoadException: NMSMethod: getWorldServer
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMS.initialize(NMS.java:95)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:105)
[10:04:37 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[10:04:37 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192)
[10:04:37 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:04:37 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:04:37 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[10:04:37 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:637)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[10:04:37 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1103)
[10:04:37 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[10:04:37 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:04:37 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "com.divisionind.bprm.nms.reflect.NMS.DIMENSION_MANAGER_OVERWORLD" is null
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMSMethod.lambda$static$1(NMSMethod.java:52)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMSMethod.fuzzyMethodLookup(NMSMethod.java:110)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMSMethod.lambda$static$2(NMSMethod.java:49)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMSMethod.init(NMSMethod.java:95)
[10:04:37 WARN]: 	at BackpacksRemastered-2022.1.8.jar//com.divisionind.bprm.nms.reflect.NMS.initialize(NMS.java:93)
[10:04:37 WARN]: 	... 13 more
[10:04:37 INFO]: [BackpacksRemastered] BackpacksRemastered v2022.1.8 (git: 87134ed) was enabled in 0.04s!

**Comment by TheIceMagmaCube** [comment]
I have the same issue, so far it still works on my server.
I didn't notice any bug or issue so far, I'll look for them and report what I'll found on the GitHub.

**Comment by DmitryASmith** [comment]
> I have the same issue, so far it still works on my server. I didn't notice any bug or issue so far, I'll look for them and report what I'll found on the GitHub.

In my tutorial version of p1194, only ovens don't work. The rest of the backpacks work. Confirm this who can.

To the developer) Thank you for the development! The idea is really cool.
From myself, a wish that affects the behavior of players: 
1.it would be cool if the recipes for all backpacks appeared after crafting the key.
2.setting the color of the backpack in the config, for the logic of the ingredients used in the recipes.

As for the error...
I've been tinkering with the decompiled code of this plugin a little, but I'm still far from developing in java and could not figure out the version selection algorithm for using the API. 

my log of a broken furnace (error after opening the knapsack with the furnace)
[Log.txt] (https://github.com/divisionind/BackpacksRemastered/files/11105321/Log.txt)
