### ISSUE TITLE
[BUG] Furnace Backpack in Combined Backpack does nothing (V2022.1.8)

### ISSUE THREAD

**Issue by DGAlbipe** [divisionind/BackpacksRemastered#48]
**Furnace Backpack in Combined Backpack does nothing**
I was using a Combined Backpack that is combined with a Netherite Chestplate, The Furnace GUI doesn't pop up and after clicking the Furnance Backpack it doesn't allow you to use backpacks anymore (unless you restart the server)
**To Reproduce**
1. Make a Combined Backpack
2. Combine it with a Netherite Chestplate
3. Make a Furnace Backpack
4. Combine the Combined Backpack with Furnace Backpack
5. Click on the Furnace inside the Combined Backpack

**Expected behavior**
Furnace GUI and I can smelt items

**Screenshots**
None

**Version info**
Spigot 1.20 (3797)

**Additional context**
None

**Comment by DmitryASmith** [comment]
Yes, I have the same problem with the oven in the combination backpack and without. I tried to override known versions (in NMS), but I don't know the methods, so the plugin didn't work, it breaks.
console log:
```
[01:36:57 INFO]: [BackpacksRemastered] Enabling BackpacksRemastered v2022.1.8
[01:36:57 ERROR]: Error occurred while enabling BackpacksRemastered v2022.1.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.divisionind.bprm.nms.KnownVersion.before()" because "com.divisionind.bprm.nms.KnownVersion.v1_16_R1" is null
	at com.divisionind.bprm.Backpacks.onEnable(Backpacks.java:91) ~[BackpacksRemastered-2022.1.8b3.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-18]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-18]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.20.1.jar:git-Paper-18]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.20.1.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-18]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-18]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-18]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by elricers** [comment]
The same happened here i had to reset the server to get it to work

**Comment by DmitryASmith** [comment]
What version are you testing on?
Today specially rechecked on server version 1.20.1 BUG is reproduced.
Also found another one: After using the key on backpacks with 27 slots (LINKED or SMALL), you can not remove or put items from them before performing a relogon.

Just in case, I once again attach the log of the unmodified plugin when using the key on the type "FURNANS"...
`[ ERROR]: Could not pass event PlayerInteractEvent to BackpacksRemastered v2022.1.8
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because the return value of "com.divisionind.bprm.nms.reflect.NMSMethod.getMethod()" is null
	at com.divisionind.bprm.nms.reflect.NMS.getWorldServer(NMS.java:107) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.divisionind.bprm.backpacks.BPFurnace.openBackpack(BPFurnace.java:82) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.divisionind.bprm.events.BackpackOpenCloseEvent.onBackpackOpen(BackpackOpenCloseEvent.java:65) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor326.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-84]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:10:13 ERROR]: Could not pass event PlayerInteractEvent to BackpacksRemastered v2022.1.8
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.invoke(Object, Object[])" because the return value of "com.divisionind.bprm.nms.reflect.NMSMethod.getMethod()" is null
	at com.divisionind.bprm.nms.reflect.NMS.getWorldServer(NMS.java:107) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.divisionind.bprm.backpacks.BPFurnace.openBackpack(BPFurnace.java:82) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.divisionind.bprm.events.BackpackOpenCloseEvent.onBackpackOpen(BackpackOpenCloseEvent.java:65) ~[BackpacksRemastered-2022.1.8.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor326.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-84]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-84]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-84]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:537) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-84]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-84]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`


I hope that the authors will take care of this soon)

UPD: I rebuilt the plugin (slightly modified NMSVersions) with BETTA242 The error remained. But I still haven't figured out the calls in the NMS classes that have changed since version 1193 (The error stretches from there).

UPD2:It seems to me that the methods need to be overridden in NMS.java and NMSMethod.java. Who is good at JAVA, take a look when you have free time.

**Comment by elricers** [comment]
the version I was testing was 
BackpacksRemastered-2022.1.8.jar

**Comment by DmitryASmith** [comment]
> the version I was testing was BackpacksRemastered-2022.1.8.jar

I think we're talking about different things. I wrote above that I'm testing plugin version 2022.1.8 on server 1.20.1. You probably missed it.
